version: 2
jobs:
  build:
    docker:
      - image: texlive/texlive-full
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y curl
      - run:
          name: Build PDF
          command: ./compile.sh
